.\" Man page for jstop
.\" Licensed under CC-BY-SA
.\" Created by Marc-André Pelletier
.\"
.TH JSTOP 1 2014-08-21 1.0.11 "Wikimedia Labs Tools jobutils"
.SH NAME
jstop \- delete a job from the grid
.SH SYNOPSIS
.B jstop
.I jobname
.SH DESCRIPTION
.B jstop
deletes the job with the name
.I jobname
from the grid.
.SH AUTHORS
Marc-André Pelletier, Petr Bena
