.\" Man page for jstart
.\" Licensed under CC-BY-SA
.\" Created by Marc-André Pelletier
.\"
.TH Jobutils "jstop" "User Manual"
.SH NAME
usage: jstop [jobname]

Delete a job

.SH DESCRIPTION
jobutils will insert extra commands to grid engine, these tools were created for wikimedia tools project
.PP
.SH "AUTHOR"
Marc-André Pelletier, Petr Bena
.br
