.TH RMTOOL 8 2014-04-01 1.0.8dev "Wikimedia Labs Tools misctools"
.SH NAME
rmtool \- remove a tool account's data
.SH SYNOPSIS
.B rmtool
.I tool
.SH DESCRIPTION
.B rmtool
removes a tool account's data and backs it up under
.IR /data/project/.system/removed_tools .
.SH EXIT STATUS
If the tool account's data was successfully removed and backed up,
.B rmtool
returns 0.  Otherwise, the exit status is greater than 0.
.SH FILES
.I /data/project/.system/removed_tools
The directory where backups of removed tool account's data are stored.
.SH AUTHORS
Marc-André Pelletier, Petr Bena
