#! /bin/bash
#
# Copyright © 2013 Marc-André Pelletier <mpelletier@wikimedia.org>
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

cd /data/project/
export HOME=/root
prefix=$(/bin/cat /etc/wmflabs-project)

while true;do

	getent passwd | grep "^$prefix\\." | cut -d : -f 1 | sed -n '/^[^.]*./{s///;p}' | while read tool; do

		if [ ! -d "$tool" ]; then
			logger -t toolwatcher "Creating tool $tool"

			mkdir "$tool"
			mkdir "$tool/public_html"
			mkdir "$tool/cgi-bin"
			chmod -R g+rw,o+r "$tool"
			chown -R "$prefix.$tool:$prefix.$tool" "$tool"
			find "$tool" -type d | xargs chmod g+sx,o+x
		fi

	done

	sleep 120

done

