.TH TOOLWATCHER 8 2014-08-21 1.0.10 "Wikimedia Labs Tools misctools"
.SH NAME
toolwatcher \- create home directories for tool accounts
.SH SYNOPSIS
.B toolwatcher
.SH DESCRIPTION
.B toolwatcher
is a daemon that creates a basic directory structure with useful
permissions for (new) tool accounts.  This encompasses the home
directory and two subdirectories
.I cgi-bin
and
.I public_html
with the permissions u=rwx,g=rwsx,o=rx.
.SH EXIT STATUS
.B toolwatcher
does not return.
.SH AUTHORS
Marc-André Pelletier, Petr Bena
