#! /bin/bash
#
# Copyright © 2013 Marc-André Pelletier <mpelletier@wikimedia.org>
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

export HOME=/root
while true;do
	cd /data/project/
	for tool in $(getent passwd | cut -d : -f 1 | sed -n '/^local-/{s///;p}'); do
		if [ ! -d "/data/project/$tool" ]; then
			logger -t toolwatcher "Creating tool $tool"

			mkdir "$tool"
			mkdir "$tool/public_html"
			mkdir "$tool/cgi-bin"
			chmod -R g+rw,o+r "$tool"
			chown -R "local-$tool:local-$tool" "$tool"
			find "$tool" -type d | xargs chmod g+sx,o+x
		fi

    if [ -r $tool/replica.my.cnf -a ! -r /data/project/.system/cache/localdb-$tool ]; then
      user="$(sed -n -e "/user='\(.*\)'/{;s//\1/;p;}" $tool/replica.my.cnf)"
      password="$(sed -n -e "/password='\(.*\)'/{;s//\1/;p;}" $tool/replica.my.cnf)"
      /usr/bin/mysql -h tools-db -u root <<-END
        grant usage on *.* to '$user'@'%' identified by '$password';
        grant all privileges on \`${user}__%\`.* to '$user'@'%' with grant option;
        grant select on \`%_p\`.* to '$user'@'%';
END
      touch /data/project/.system/cache/localdb-$tool
    fi

		if ! grep -q "^$tool " /data/project/.system/webservers >/dev/null; then
      echo "add '$tool' to webservers again?"
			echo "$tool tools-webserver-01" >>/data/project/.system/webservers
		fi
	done
	cd /tmp
	sleep 120
done

